# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0db288444830404a860f89561b6acd9371f96fc56d9d39e0ea3f4f77bfc57f241053544000696458bb8ea0dbc2127fecb37ae742a34d893ce093b04daaff956

test:
  secret_key_base: 097dfe435b0988a6741a1050b41d61ada8dcccdc9605fd0c49f27c1172c0de739827083ce2d4a7c016a65feabbd7b2352cda095db77f599eede09f57f8d46594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
